const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{once,EventEmitter}=require('node:events'),{PassThrough}=require('node:stream');
const {Settings,normalizeGateway}=require('../src/main/settings.cjs'),{Service,policy}=require('../src/main/service.cjs'),{streamChat}=require('../src/main/http.cjs'),{createWorker}=require('../src/main/worker.cjs'),{download}=require('../src/main/downloads.cjs');
async function server(t,fn){const s=http.createServer(fn);s.listen(0,'127.0.0.1');await once(s,'listening');t.after(()=>{s.closeAllConnections();s.close();});return 'http://127.0.0.1:'+s.address().port;}
function config(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'common-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {settings:new Settings(dir),dir};}
const answer='data: {"choices":[{"delta":{"content":"fixture 🌿"}}]}\n\ndata: [DONE]\n\n';
test('settings persist and credentials remain gateway-specific',t=>{const {settings,dir}=config(t);settings.update({gateway:'https://one.example/',chatToken:'one',idleOnly:false});settings.update({gateway:'https://two.example',chatToken:'two'});const next=new Settings(dir);assert.equal(next.value.chatTokens['https://one.example'],'one');assert.equal(next.value.chatTokens['https://two.example'],'two');assert.equal(next.value.idleOnly,false);assert.equal('chatTokens'in next.public(),false);assert.equal('identities'in next.public(),false);});
test('settings reject unsupported model tags, credentials in URLs and invalid concurrency',t=>{const {settings}=config(t);assert.throws(()=>normalizeGateway('https://user:pass@example.com'));assert.throws(()=>settings.update({model:'x:cloud'}));assert.throws(()=>settings.update({concurrency:10}));});
test('idle and battery policies pause and resume correctly',()=>{const s={contributing:true,idleOnly:true,idleMinutes:5,pauseBattery:true};assert.match(policy(s,{battery:false,idleSeconds:299}),/idle/);assert.equal(policy(s,{battery:false,idleSeconds:300}),null);assert.equal(policy(s,{battery:true,idleSeconds:999}),'Paused on battery');assert.equal(policy(s,{battery:false,idleSeconds:999,suspended:true}),'Computer asleep');});
test('SSE preserves split Unicode and routing metadata',async t=>{const url=await server(t,(_q,r)=>{r.setHeader('X-Common-Node','fixture');const bytes=Buffer.from(answer);for(let i=0;i<bytes.length;i+=3)r.write(bytes.subarray(i,i+3));r.end();});let text='';const out=await streamChat(url,{}, {},AbortSignal.timeout(2000),d=>text+=d);assert.equal(text,'fixture 🌿');assert.equal(out.receipt.node,'fixture');});
test('incomplete SSE is reported as interrupted',async t=>{const url=await server(t,(_q,r)=>r.end('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n'));await assert.rejects(streamChat(url,{}, {},AbortSignal.timeout(2000),()=>{}),/before the answer finished/);});
test('malformed SSE is rejected',async t=>{const url=await server(t,(_q,r)=>r.end('data: {broken}\n\n'));await assert.rejects(streamChat(url,{}, {},AbortSignal.timeout(2000),()=>{}));});
test('worker authentication, allowlist, model pinning and streaming match the baseline',async t=>{let forwarded=0;const upstream=await server(t,async(q,r)=>{let body='';for await(const c of q)body+=c;assert.equal(JSON.parse(body).model,'test');forwarded++;r.end(answer);});const w=await createWorker({model:'test',token:'fixture-token',ollama:upstream});t.after(()=>w.close());const url='http://127.0.0.1:'+w.port,headers={Authorization:'Bearer fixture-token'};assert.equal((await fetch(url+'/v1/models')).status,401);assert.equal((await fetch(url+'/api/pull',{method:'POST',headers,body:'{}'})).status,404);assert.equal((await fetch(url+'/v1/chat/completions',{method:'POST',headers,body:JSON.stringify({model:'wrong',messages:[]})})).status,400);const r=await fetch(url+'/v1/chat/completions',{method:'POST',headers,body:JSON.stringify({model:'test',messages:[],stream:true})});assert.equal(await r.text(),answer);assert.equal(forwarded,1);assert.equal(w.stats.completed,1);assert.equal(JSON.stringify(w.stats).includes('fixture'),false);});
test('worker concurrency and pause cancel active inference',async t=>{let mark;const started=new Promise(r=>mark=r),upstream=await server(t,(_q,r)=>{mark();r.write('data: ');});const w=await createWorker({model:'test',token:'token',ollama:upstream});t.after(()=>w.close());const url='http://127.0.0.1:'+w.port+'/v1/chat/completions',o={method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({model:'test',messages:[],stream:true})};const first=fetch(url,o);await started;assert.equal((await fetch(url,o)).status,503);w.pause();await first.then(r=>r.text()).catch(()=>{});assert.equal((await fetch(url,o)).status,503);});
test('download checksums and temporary-file cleanup',async t=>{const {dir}=config(t),url=await server(t,(_q,r)=>r.end('fixture')),file=path.join(dir,'file');await download(url,file);assert.equal(fs.readFileSync(file,'utf8'),'fixture');await assert.rejects(download(url,file,{sha256:'0'.repeat(64)}),/checksum/);assert.equal(fs.existsSync(file+'.part'),false);});
test('model pull reports progress and verifies installed inventory',async t=>{let installed=false;const url=await server(t,(q,r)=>{if(q.url==='/api/pull'){installed=true;r.end('{"status":"pulling","total":100,"completed":50}\n{"status":"success"}\n');}else if(q.url==='/api/tags')r.end(JSON.stringify({models:installed?[{name:'llama3.2:3b'}]:[]}));else r.end('{"models":[],"version":"fixture"}');});const {settings,dir}=config(t);settings.update({gateway:url});const s=new Service(settings,{dataDir:dir,openPath:async()=>'',ollama:url});t.after(()=>s.close());let seen=false;s.on('state',v=>{if(v.download?.completed===50)seen=true;});await s.pullModel();assert.equal(seen,true);assert.equal(s.state.ollama.models.length,1);assert.equal(s.state.download.done,true);});
test('cancelled pulls do not mark a model installed',async t=>{let mark;const started=new Promise(r=>mark=r),url=await server(t,(_q,r)=>{r.write('{"status":"pulling","total":100,"completed":1}\n');mark();});const {settings,dir}=config(t),s=new Service(settings,{dataDir:dir,openPath:async()=>'',ollama:url});t.after(()=>s.close());const pending=s.pullModel();await started;s.cancelDownload();await pending;assert.match(s.state.download.status,/Paused/);assert.equal(s.state.ollama.models.length,0);});
test('network credentials are absent from local chat requests',async t=>{const seen=[],url=await server(t,(q,r)=>{seen.push(q.headers['x-common-node-token']);r.end(answer);});const {settings,dir}=config(t);settings.update({gateway:url,chatToken:'fixture-token'});const s=new Service(settings,{dataDir:dir,openPath:async()=>'',ollama:url});t.after(()=>s.close());for(const target of ['network','local'])await s.chat({messages:[{role:'user',content:'fixture'}],target});assert.deepEqual(seen,['fixture-token',undefined]);});
test('registration, dropped-tunnel recovery and pause clean up the baseline worker',async t=>{const requests=[],children=[],url=await server(t,async(q,r)=>{let body='';for await(const c of q)body+=c;requests.push({method:q.method,url:q.url,headers:q.headers,body:body?JSON.parse(body):null});r.end(q.method==='POST'?'{"id":"fixture-id","node_token":"owner-token"}':'{}');});const {settings,dir}=config(t);settings.update({gateway:url,contributing:true,idleOnly:false});fs.mkdirSync(path.join(dir,'bin'));fs.writeFileSync(path.join(dir,'bin',process.platform==='win32'?'cloudflared.exe':'cloudflared'),'fixture');const spawnTunnel=()=>{const c=new EventEmitter();c.stdout=new PassThrough();c.stderr=new PassThrough();c.exitCode=null;c.killed=false;c.kill=()=>{c.killed=true;c.exitCode=0;c.emit('exit',0);};children.push(c);setImmediate(()=>c.stdout.write('https://fixture.trycloudflare.com\n'));return c;};const s=new Service(settings,{dataDir:dir,openPath:async()=>'',spawnTunnel});t.after(()=>s.close());s.state.ollama={online:true,models:[{name:'llama3.2:3b'}],running:[]};await s.reconcile();assert.equal(s.state.worker.status,'Contributing');assert.ok(requests[0].body.worker_token.length>=16);assert.equal(requests[0].body.endpoint_url,'https://fixture.trycloudflare.com/v1');const port=s.worker.port;children[0].exitCode=1;children[0].emit('exit',1);await s.tail;assert.equal(children.length,2);await assert.rejects(fetch('http://127.0.0.1:'+port+'/v1/models'));await s.update({contributing:false});assert.equal(s.worker,null);assert.equal(children[1].killed,true);assert.equal(requests.filter(r=>r.method==='DELETE').at(-1).headers['x-common-node-token'],'owner-token');});
