const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{once}=require('node:events');
const {secureStorage}=require('./fixtures.cjs'),{Diagnostics,sanitise}=require('../src/main/diagnostics.cjs'),{Settings}=require('../src/main/settings.cjs'),{Service}=require('../src/main/service.cjs'),{Reporting}=require('../src/main/observability.cjs'),{Performance}=require('../src/main/performance.cjs'),{createWorker}=require('../src/main/worker.cjs'),{failure}=require('../src/main/errors.cjs'),{createUpdates}=require('../src/main/updater.cjs');
function dir(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'common-observe-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p;}
async function server(t,fn){const s=http.createServer(fn);s.listen(0,'127.0.0.1');await once(s,'listening');t.after(()=>{s.closeAllConnections();s.close();});return 'http://127.0.0.1:'+s.address().port;}
function service(t,gateway){const p=dir(t),settings=new Settings(p,{secureStorage});if(gateway)settings.update({gateway});const s=new Service(settings,{dataDir:p,ollama:gateway,openPath:async()=>'',identity:{forGateway:()=>null,clear(){}}});t.after(()=>s.close());return s;}
const synthetic='{"response":"OK","done":false}\n{"done":true,"eval_count":2,"prompt_eval_count":4,"eval_duration":200000000}\n';
const sse='data: {"choices":[{"delta":{"content":"OK"}}]}\n\ndata: {"choices":[{"finish_reason":"stop","delta":{}}],"usage":{"prompt_tokens":3,"completion_tokens":2,"total_tokens":5}}\n\ndata: [DONE]\n\n';
test('one sanitiser drops secrets, paths, arbitrary text and nested unknown fields',()=>{const data=sanitise({prompt:'secret',response:'secret',Authorization:'secret',worker_token:'secret',username:'secret',filename:'secret',model:'alice/private-model:latest',error:{message:'/Users/alice/token',code:'INFERENCE_FAILED',causeType:'TypeError'},events:[{event:'job_completed',completionTokens:10,prompt:'secret',environment:{TOKEN:'secret'},model:'qwen3:8b'}],computer:{cpu:'Alice workstation',ramGB:16}});assert.ok(!JSON.stringify(data).includes('secret'));assert.ok(!JSON.stringify(data).includes('alice'));assert.equal(data.model,'custom-model');assert.equal(data.events[0].completionTokens,10);assert.equal(data.error.code,'INFERENCE_FAILED');});
test('bounded logs survive restart, preserve statistics and detect unexpected exit',t=>{let now=Date.now();const p=dir(t),d=new Diagnostics(p,{now:()=>now});for(let i=0;i<1010;i++)d.record('job_received',{prompt:'secret'});d.job({success:true,completionTokens:20,ttftMs:100,tokensPerSecond:5,totalMs:4000});d.tick(true);const next=new Diagnostics(p,{now:()=>now});assert.equal(next.unexpectedExit,true);assert.equal(next.stats().allTime.tokensGenerated,20);assert.equal(next.stats().session.jobsCompleted,0);assert.equal(next.data.events.length,1000);now+=8*86400000;next.record('app_started');assert.equal(next.data.events.length,1);assert.equal(next.data.activity.length,0);assert.equal(next.stats().today.jobsCompleted,0);next.close();assert.equal(new Diagnostics(p).unexpectedExit,false);assert.ok(fs.statSync(next.file).size<1024*1024);});
test('settings migrate credentials atomically and never fall back to plaintext',t=>{const p=dir(t);fs.writeFileSync(path.join(p,'settings.json'),JSON.stringify({chatTokens:{'https://example.com':'private-token'},identities:{}}));const s=new Settings(p,{secureStorage});assert.equal(s.value.chatTokens['https://example.com'],'private-token');assert.ok(!fs.readFileSync(s.file,'utf8').includes('private-token'));assert.ok(!fs.readFileSync(s.credentials.file).includes(Buffer.from('private-token')));assert.equal(new Settings(p,{secureStorage}).value.chatTokens['https://example.com'],'private-token');assert.throws(()=>new Settings(p,{secureStorage:{isEncryptionAvailable:()=>false}}),{code:'SECURE_STORAGE_UNAVAILABLE'});const blocked=new Settings(dir(t));assert.throws(()=>blocked.update({chatToken:'not-persisted'}),{code:'SECURE_STORAGE_UNAVAILABLE'});assert.equal(blocked.value.chatTokens[blocked.value.gateway],undefined);});
test('OS plaintext backend is rejected',t=>{const s=new Settings(dir(t),{secureStorage:{...secureStorage,getSelectedStorageBackend:()=> 'basic_text'}});assert.throws(()=>s.update({chatToken:'secret'}),{code:'SECURE_STORAGE_UNAVAILABLE'});});
test('telemetry is opt-in and revocation drops pending events',async t=>{const seen=[],url=await server(t,async(q,r)=>{let body='';for await(const c of q)body+=c;seen.push(JSON.parse(body));r.end('{"accepted":true}');}),s=service(t,url);s.record('chat_started',{prompt:'secret'});await s.reporting.flush();assert.equal(seen.length,0);s.settings.update({telemetry:true});s.record('chat_completed',{prompt:'secret',totalMs:123});await s.reporting.flush();assert.equal(seen.length,1);assert.ok(!JSON.stringify(seen).includes('secret'));assert.equal(seen[0].events[0].totalMs,123);s.record('chat_started');await s.update({telemetry:false});assert.equal(s.reporting.queue.length,0);});
test('feedback succeeds only after storage acknowledgment and excludes diagnostics unless requested',async t=>{let body,accepted=true;const url=await server(t,async(q,r)=>{let raw='';for await(const c of q)raw+=c;body=JSON.parse(raw);r.end(JSON.stringify({accepted,id:body.id}));}),s=service(t,url);const input={mode:'feedback',category:'general',text:'A deliberate report',rating:5,attach:true};const result=await s.reporting.report(input);assert.match(result.id,/^COMMON-\d{8}-\d{4}-[A-F0-9]{8}$/);assert.equal(body.diagnostics,null);accepted=false;await assert.rejects(s.reporting.report(input),{code:'REPORT_FAILED'});});
test('local setup exercises synthetic inference and rejects a deleted model on next launch',async t=>{let present=true,calls=0;const url=await server(t,(q,r)=>{if(q.url==='/api/tags')r.end(JSON.stringify({models:present?[{name:'llama3.2:3b',digest:'one'}]:[]}));else if(q.url==='/api/generate'){calls++;r.end(synthetic);}else if(q.url==='/health')r.end('{"status":"ok"}');else r.end('{"models":[],"version":"0.1.0"}');}),s=service(t,url);let result=await s.testSetup({target:'local',contributor:false});assert.equal(result.ready,true);assert.equal(calls,1);assert.equal(result.stages.find(s=>s.stage==='networkInference').status,'skipped');await s.update({setupComplete:true});present=false;result=await s.testSetup({target:'local',contributor:false});assert.equal(result.ready,false);assert.equal(result.stages.find(s=>s.stage==='model').code,'MODEL_NOT_INSTALLED');assert.equal(s.settings.value.setupComplete,true);});
test('settings alone never complete onboarding',async t=>{const s=service(t);await assert.rejects(s.update({setupComplete:true}),/Run Test my setup/);assert.equal(s.settings.value.setupComplete,false);});
test('malformed gateway health is not treated as ready',async t=>{const url=await server(t,(_q,r)=>r.end('{"surprise":true}')),s=service(t,url);await s.refreshGateway();assert.equal(s.state.gateway.online,false);assert.equal(s.state.gateway.code,'GATEWAY_MALFORMED');});
test('chat-only network setup validates credentials with a real request',async t=>{let authorized=false;const url=await server(t,(q,r)=>{if(q.url==='/health')return r.end('{"status":"ok"}');if(!authorized){r.statusCode=401;return r.end('{"detail":"the network answers its contributors."}');}r.end(sse);}),s=service(t,url);s.settings.update({role:'chat'});let result=await s.testSetup({target:'network',contributor:false});assert.equal(result.ready,false);assert.equal(result.stages.find(s=>s.stage==='networkInference').code,'GATEWAY_AUTH_FAILED');authorized=true;result=await s.testSetup({target:'network',contributor:false});assert.equal(result.ready,true);});
test('expired registration and unreachable worker are separate codes',async t=>{let status=404;const url=await server(t,(_q,r)=>{r.statusCode=status;r.end(status===200?'{"healthy":false}':'{}');}),s=service(t,url);s.settings.value.identities[url]={id:'fixture',node_token:'secret'};s.registeredGateway=url;await assert.rejects(s.verifyWorker(),{code:'REGISTRATION_EXPIRED'});status=200;await assert.rejects(s.verifyWorker(),{code:'WORKER_UNREACHABLE'});});
test('recovery backs off, preserves cooldown and pauses on sleep',async t=>{const s=service(t);s.settings.update({contributing:true,idleOnly:false});let starts=0;s.startWorker=async()=>{starts++;throw failure('GATEWAY_UNREACHABLE');};await s.reconcile();const first=s.retryAfter-Date.now();assert.ok(first>=4900);await s.reconcile();assert.equal(starts,1);s.retryAfter=0;await s.reconcile();assert.ok(s.retryAfter-Date.now()>first);s.power=()=>({suspended:true});await s.reconcile();assert.equal(s.state.worker.status,'Computer asleep');s.lastError={code:'TUNNEL_RATE_LIMITED'};s.retryAfter=Date.now()+600000;await assert.rejects(s.retryNow(),{code:'TUNNEL_RATE_LIMITED'});});
test('worker HTTP errors, incomplete streams and timeouts are counted as failed jobs',async t=>{let mode='http';const url=await server(t,(q,r)=>{q.resume();if(mode==='http'){r.statusCode=500;r.end('secret');}else if(mode==='partial')r.end('data: {"choices":[{"delta":{"content":"private"}}]}\n\n');else r.write('data: ');}),jobs=[],w=await createWorker({model:'test',token:'token',ollama:url,timeoutMs:50,onJob:m=>jobs.push(m)});t.after(()=>w.close());for(const m of ['http','partial','hang']){mode=m;await fetch('http://127.0.0.1:'+w.port+'/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer token'},body:JSON.stringify({model:'test',messages:[],stream:true})}).then(r=>r.text()).catch(()=>{});}await new Promise(r=>setImmediate(r));assert.equal(w.stats.failed,3);assert.equal(w.stats.completed,0);assert.equal(jobs.at(-1).code,'INFERENCE_TIMEOUT');assert.ok(!JSON.stringify(jobs).includes('private'));});
test('timing never invents token counts or internal queue time',()=>{let now=100;const p=new Performance({model:'test',now:()=>now});p.start();now=200;p.item({choices:[{delta:{content:'secret'}}]});now=500;const m=p.finish(true);assert.equal(m.completionTokens,null);assert.equal(m.tokensPerSecond,null);assert.equal(m.queueDelayMs,null);assert.equal(m.inferenceStart,null);assert.equal(m.ttftMs,100);assert.ok(!JSON.stringify(m).includes('secret'));});
test('unsigned builds never activate an executable updater',async()=>{let state;const updates=createUpdates({isPackaged:false},{state:{},emitState(){state=this.state.update;}});assert.match(state.message,/blocked/);await updates.check();await assert.rejects(updates.install(),{code:'UPDATE_FAILED'});});
for(const installed of [false,true])test(installed?'installed but stopped Ollama has a distinct error':'absent Ollama has a distinct error',async t=>{const {EventEmitter}=require('node:events');const url=await server(t,(_q,r)=>{r.statusCode=503;r.end('{}');}),p=dir(t),settings=new Settings(p,{secureStorage});settings.update({gateway:url});const s=new Service(settings,{dataDir:p,ollama:url,identity:{forGateway:()=>null},ollamaAttempts:2,ollamaDelay:1,spawnOllama:()=>{const c=new EventEmitter();c.kill=()=>{};setImmediate(()=>c.emit(installed?'spawn':'error',new Error('Synthetic spawn result')));return c;}});t.after(()=>s.close());await assert.rejects(s.startOllama(),{code:installed?'OLLAMA_NOT_RUNNING':'OLLAMA_NOT_INSTALLED'});});
test('endpoint propagation retries the same address without recreating its tunnel',async t=>{let calls=0;const url=await server(t,(_q,r)=>{calls++;if(calls<3){r.statusCode=502;r.end('{}');}else r.end('{"data":[{"id":"fixture"}]}');}),s=service(t,url);await s.probeEndpoint(url,'token','fixture',{attempts:3,delay:1});assert.equal(calls,3);});
test('app shutdown aborts a hanging local synthetic inference',async t=>{let reached;const ready=new Promise(r=>reached=r);const url=await server(t,(q,r)=>{if(q.url==='/api/generate'){reached();r.write('{"response":"O","done":false}\n');}else if(q.url==='/api/tags')r.end('{"models":[{"name":"llama3.2:3b"}]}');else if(q.url==='/health')r.end('{"status":"ok"}');else r.end('{}');}),s=service(t,url);const pending=s.testSetup({target:'local',contributor:false});await ready;await s.close();const result=await pending;assert.equal(result.ready,false);assert.equal(s.diagnostics.data.running,false);});
