const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{JSDOM}=require('jsdom'),{Settings}=require('../src/main/settings.cjs'),{FALLBACK_MODELS}=require('../src/main/service.cjs');
const html=fs.readFileSync(path.join(__dirname,'../src/renderer/index.html'),'utf8'),script=fs.readFileSync(path.join(__dirname,'../src/renderer/app.js'),'utf8'),md=fs.readFileSync(path.join(__dirname,'../src/renderer/markdown.js'),'utf8'),tick=()=>new Promise(r=>setImmediate(r));
async function fixture(t,overrides={},answer='<img src=x onerror=alert(1)> 🌿'){const state={settings:{...new Settings('/nonexistent-common-fixture').public(),...overrides},hardware:{platform:'win32',arch:'x64',ram:16*1024**3,freeRam:10*1024**3,freeDisk:200*1024**3,cpu:'Fixture CPU',cores:8},ollama:{online:true,models:[],running:[],version:'fixture'},models:FALLBACK_MODELS,gateway:{online:true},worker:{status:'Paused',active:0,completed:0,failed:0,bytes:0},power:{battery:false,idleSeconds:0},download:null},dom=new JSDOM(html,{runScripts:'outside-only',url:'file:///common/index.html'});t.after(()=>dom.window.close());const w=dom.window;let listener=()=>{},delta=()=>{},sent,inspect=()=>{},navigate=()=>{};const opened=[];w.common={onNavigate:fn=>{navigate=fn;return()=>{};},testSetup:async()=>({ready:true,stages:[]}),openLink:async u=>{opened.push(u);},snapshot:async()=>structuredClone(state),refresh:async()=>structuredClone(state),onState:fn=>listener=fn,onChatDelta:fn=>delta=fn,update:async p=>{Object.assign(state.settings,p);listener(structuredClone(state));return structuredClone(state);},pullModel:async()=>{state.ollama.models=[{name:state.settings.model}];listener(structuredClone(state));},prepareTunnel:async()=>'/fixture/helper',cancelDownload:async()=>{},chat:async p=>{sent=p;const content=answer;delta(content);inspect();return {content,receipt:{node:'fixture'}};},cancelChat:async()=>{},hide:async()=>{},quit:async()=>{},openHelp:async()=>{}};w.eval(md);w.eval(script);await tick();return {w,state,opened,setInspect:fn=>{inspect=fn;},ask:async text=>{const p=w.document.querySelector('#prompt');p.value=text;p.dispatchEvent(new w.Event('input'));w.document.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();},sent:()=>sent,emit:()=>listener(structuredClone(state)),navigate:v=>navigate(v),click:async selector=>{const b=w.document.querySelector(selector);assert.ok(b,'Missing '+selector);b.click();await tick();}};}
test('onboarding installs a fixture model and opens chat',async t=>{const {w,state,click}=await fixture(t,{role:'chat'});for(let i=0;i<3;i++)await click('[data-action=next]');await click('[data-action=pullModel]');await click('[data-action=next]');await click('[data-action=next]');await click('[data-action=finish]');assert.equal(state.settings.setupComplete,true);assert.equal(state.settings.contributing,false);assert.ok(w.document.querySelector('#chatForm'));});
test('three information levels reveal appropriate diagnostics',async t=>{const {w,click}=await fixture(t,{setupComplete:true});assert.ok(w.document.querySelector('[data-tab=diagnostics]'));await click('[data-level=enthusiast]');await click('[data-tab=contribute]');assert.ok(w.document.querySelector('#liveHardware'));await click('[data-level=developer]');await click('[data-tab=diagnostics]');assert.ok(w.document.querySelector('#diagnosticsJson'));await click('[data-level=user]');assert.ok(w.document.querySelector('#diagnosticsJson'));});
test('chat output stays plain text and destination change resets context',async t=>{const {w,sent}=await fixture(t,{setupComplete:true});const p=w.document.querySelector('#prompt');p.value='fixture prompt';p.dispatchEvent(new w.Event('input'));w.document.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(sent().messages[0].content,'fixture prompt');assert.equal(w.document.querySelectorAll('.message img').length,0);assert.match(w.document.querySelector('.message.assistant').textContent,/<img/);const target=w.document.querySelector('#target');target.value='local';target.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.message').length,0);});
test('assistant answers render as markdown and user messages do not',async t=>{const {w,ask}=await fixture(t,{setupComplete:true},'## Title\n\nSome **bold** and `code`.\n\n- one\n- two\n\n```js\nconst a=1;\n```');await ask('**not bold**');const md=w.document.querySelector('.message.assistant .md');assert.ok(md);assert.equal(md.querySelector('h4').textContent,'Title');assert.equal(md.querySelector('strong').textContent,'bold');assert.equal(md.querySelectorAll('li').length,2);assert.equal(md.querySelector('pre.mdcode').dataset.lang,'js');assert.equal(w.document.querySelector('.message.user strong'),null);assert.match(w.document.querySelector('.message.user').textContent,/\*\*not bold\*\*/);});
test('markdown links open through the main process instead of navigating',async t=>{const {w,ask,opened}=await fixture(t,{setupComplete:true},'See [Common](https://commonai.com.au) and [nope](javascript:alert(1)).');await ask('links please');const link=w.document.querySelector('.message.assistant a.mdlink');assert.equal(link.dataset.link,'https://commonai.com.au/');assert.equal(w.document.querySelectorAll('.message.assistant a').length,1);link.dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}));await tick();assert.deepEqual(opened,['https://commonai.com.au/']);});
test('streamed answers re-render markdown as they arrive',async t=>{const {w,ask,setInspect}=await fixture(t,{setupComplete:true},'- streamed item');let seen=null;setInspect(()=>{seen=w.document.querySelector('.message.assistant .md li')?.textContent;});await ask('stream');assert.equal(seen,'streamed item');});
// A network answer served by this machine is the case the reader most needs
// named, and User level -- the default -- used to show no receipt at all.
test('every answer names the worker that produced it, this computer included',async t=>{const {w,ask}=await fixture(t,{setupComplete:true,name:'common-2fea082fc9'});
 await ask('who answered');
 assert.equal(w.document.querySelector('.receipt').textContent,'Answered by fixture');
 w.common.chat=async()=>({content:'mine',receipt:{node:'common-2fea082fc9'}});
 await ask('and now');
 assert.match(w.document.querySelector('.receipt').textContent,/this computer — your own node/);
 w.common.chat=async()=>({content:'anon',receipt:{node:null}});
 await ask('unnamed');
 assert.match(w.document.querySelector('.receipt').textContent,/did not name the worker/);});
test('the local destination is never described as the network',async t=>{const {w,ask}=await fixture(t,{setupComplete:true,model:'qwen3.5:4b'});const target=w.document.querySelector('#target');target.value='local';target.dispatchEvent(new w.Event('change'));await ask('local please');assert.equal(w.document.querySelector('.receipt').textContent,'Answered by this computer · qwen3.5:4b');});
test('live updates preserve unsaved connection inputs',async t=>{const {w,click,emit}=await fixture(t,{setupComplete:true});await click('[data-tab=settings]');w.document.querySelector('#gatewayInput').value='https://new.example';w.document.querySelector('#tokenInput').value='fixture';emit();assert.equal(w.document.querySelector('#gatewayInput').value,'https://new.example');assert.equal(w.document.querySelector('#tokenInput').value,'fixture');});
test('cancelled helper setup cannot enable contribution',async t=>{const {w,state,click}=await fixture(t);w.common.prepareTunnel=async()=>undefined;for(let i=0;i<3;i++)await click('[data-action=next]');await click('[data-action=pullModel]');await click('[data-action=next]');await click('[data-action=next]');await click('[data-action=finish]');assert.equal(state.settings.setupComplete,false);assert.equal(state.settings.contributing,false);});
test('feedback entry exists at first run and keeps drafts across live state changes',async t=>{const {w,click,emit}=await fixture(t);await click('[data-action=feedback]');const input=w.document.querySelector('#reportText');input.value='Do not discard my report';emit();assert.equal(w.document.querySelector('#reportText').value,'Do not discard my report');});
test('a failed setup probe cannot mark onboarding complete',async t=>{const {w,state,click}=await fixture(t,{role:'chat',setupStep:5});w.common.testSetup=async()=>({ready:false,stages:[]});await click('[data-action=finish]');assert.equal(state.settings.setupComplete,false);assert.match(w.document.querySelector('#error').textContent,/Setup needs attention/);assert.ok(w.document.querySelector('#testProgress'));});
test('feedback confirms only an acknowledged submission and preserves failed text',async t=>{const {w,click}=await fixture(t,{setupComplete:true});await click('[data-tab=feedback]');w.common.report=async()=>{throw new Error('Not submitted');};let input=w.document.querySelector('#reportText');input.value='Useful feedback';w.document.querySelector('#feedbackForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(w.document.querySelector('#reportText').value,'Useful feedback');assert.ok(!w.document.querySelector('main').textContent.includes('Successfully submitted:'));w.common.report=async()=>({id:'COMMON-20260921-1842-A7F31234'});w.document.querySelector('#feedbackForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.match(w.document.querySelector('main').textContent,/Successfully submitted: COMMON-/);});

// A first-time user is shown setup and nothing else. The tray menu can ask the
// window for any tab, including the two the app chrome renders while setup is open,
// so a menu click on a machine that has never been set up must not land in the app.
test('a tray jump to diagnostics cannot put a first-time user in the app',async t=>{const {w,navigate}=await fixture(t,{setupComplete:false});navigate('diagnostics');await tick();assert.equal(w.document.querySelector('[data-tab=chat]'),null,'the tray must not reach the app chrome before setup is done');assert.equal(w.document.querySelector('#diagnosticsJson'),null);assert.ok(w.document.querySelector('.steps'),'setup is still what the window shows');navigate('chat');await tick();assert.ok(w.document.querySelector('.steps'));});
// ...but the way out of setup that setup itself offers still works, and comes back.
test('feedback stays reachable from inside setup, and returns to it',async t=>{const {w,click}=await fixture(t,{setupComplete:false});await click('[data-action=feedback]');assert.ok(w.document.querySelector('#reportText'),'the report box a stuck person needs');await click('[data-action=returnSetup]');assert.ok(w.document.querySelector('.steps'),'Return to setup goes back to the rail');assert.equal(w.document.querySelector('#reportText'),null);});
// Manage local setup reached the model step in memory only, so a restart dropped you
// back on whatever step setupStep happened to hold -- usually the last one.
test('Manage local setup records the step it jumps to',async t=>{const {state,click}=await fixture(t,{setupComplete:true,setupStep:5});await click('[data-tab=settings]');await click('[data-action=localSetup]');assert.equal(state.settings.setupComplete,false);assert.equal(state.settings.setupStep,3,'the fixture has Ollama running, so the model step');});
test('an existing user can run setup again from Settings',async t=>{const {w,state,click}=await fixture(t,{setupComplete:true,setupStep:5});await click('[data-tab=settings]');await click('[data-action=runSetup]');assert.equal(state.settings.setupComplete,false);assert.equal(state.settings.setupStep,0);assert.equal(w.document.querySelector('#chatForm'),null);assert.ok(w.document.querySelector('.steps'),'the setup rail comes back');assert.match(w.document.querySelector('#main h1').textContent,/Make yourself/);});
// Built from a real Settings on a real empty directory rather than the fixture's own
// defaults, so a later change to the defaults cannot quietly turn onboarding off and
// still pass here.
test('a fresh settings.json lands on onboarding, not the main app',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'common-fresh-')),fresh=new Settings(dir).public();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));assert.equal(fresh.setupComplete,false,'a machine that has never run Common has not completed setup');const {w}=await fixture(t,fresh);assert.equal(w.document.querySelector('[data-tab=chat]'),null,'the main navigation must wait behind setup');assert.equal(w.document.querySelector('#chatForm'),null);assert.ok(w.document.querySelector('.steps'),'the setup rail is showing');assert.match(w.document.querySelector('#main h1').textContent,/Make yourself/);});
