const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),dns=require('node:dns').promises;
const {json,checkedFetch,streamChat,gatewayHeaders}=require('./http.cjs');
const {sanitise,anonymousNode}=require('./diagnostics.cjs');
const {failure,classify,errorFields}=require('./errors.cjs');
const {Performance}=require('./performance.cjs');
const STAGES=['application','network','gateway','ollama','model','localInference','helper','publicEndpoint','registration','worker','networkInference'];
const methods={
 record(event,fields={}){return this.diagnostics.record(event,fields);},
 health(){const model=this.state.ollama.models.find(m=>m.name===this.settings.value.model||m.name===this.settings.value.model+':latest');return {gateway:this.state.gateway.online?'healthy':'unreachable',ollama:this.state.ollama.online?'healthy':'unreachable',model:model?(this.modelHealthy===this.modelKey()?'ready':'unknown'):'missing',tunnel:this.endpoint&&this.tunnel&&!this.tunnel.killed&&this.tunnel.exitCode===null?'connected':'disconnected',registration:this.registeredGateway?'active':'expired',worker:this.workerVerified?'reachable':'unknown',contribution:this.workerVerified&&this.state.worker.status==='Contributing'?'accepting jobs':'paused'};},
 modelKey(){const s=this.settings.value,m=this.state.ollama.models.find(m=>m.name===s.model||m.name===s.model+':latest');return s.model+':'+(m?.digest||'unknown');},
 helperInstalled(){return fs.existsSync(path.join(this.dataDir,'bin',process.platform==='win32'?'cloudflared.exe':'cloudflared'));},
 diagnosticReport(){const s=this.settings.value,h=this.health();return sanitise({application:{version:this.diagnostics.version,build:this.diagnostics.build,unexpectedExit:this.diagnostics.unexpectedExit},computer:{platform:process.platform,arch:process.arch,cores:os.cpus().length,ramGB:Math.round(os.totalmem()/1024**3)},ollama:{online:this.state.ollama.online,ollamaVersion:this.state.ollama.version},models:{model:s.model,status:h.model},gateway:{status:h.gateway},node:{nodeId:anonymousNode(this.node()?.id,this.diagnostics.data.installationId)},tunnel:{status:h.tunnel,installed:this.helperInstalled()},worker:{status:h.worker,active:this.state.worker.active},contribution:{status:h.contribution},recentEvents:this.diagnostics.data.events.slice(-100),statistics:this.diagnostics.stats(),performance:this.lastPerformance||{},update:{available:this.state.update?.available||false,code:this.state.update?.code}});},
 async modelHealth({benchmark=false}={}){const model=this.settings.value.model;if(!this.state.ollama.online)throw failure('OLLAMA_NOT_RUNNING');if(!this.state.ollama.models.some(m=>m.name===model||m.name===model+':latest'))throw failure('MODEL_NOT_INSTALLED');const key=this.modelKey();if(!benchmark&&this.modelHealthy===key)return this.lastBenchmark;const timing=new Performance({model});timing.start();try{const r=await checkedFetch(this.ollama+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,prompt:benchmark?'Count from one to twenty using words.':'Reply with OK.',stream:true,options:{num_predict:benchmark?64:8,temperature:0},think:false}),signal:AbortSignal.any([this.lifecycle.signal,AbortSignal.timeout(120000)])});const {lines}=require('./http.cjs');for await(const line of lines(r.body))if(line)timing.item(JSON.parse(line));if(!timing.completed||timing.m.ttftMs===null)throw new Error('No completed test answer');this.modelHealthy=key;this.lastBenchmark=timing.finish(true);this.record(benchmark?'benchmark_completed':'model_checked',this.lastBenchmark);this.diagnostics.data.benchmark=sanitise(this.lastBenchmark);this.diagnostics.save();return this.lastBenchmark;}catch(e){this.modelHealthy=null;throw failure('MODEL_HEALTH_FAILED',e);}},
 async probeEndpoint(endpoint,token,model,{attempts=12,delay=10000}={}){for(let i=0;i<attempts;i++){if(this.closed)throw failure('TUNNEL_START_FAILED');try{const r=await json(endpoint+'/v1/models',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.any([this.lifecycle.signal,AbortSignal.timeout(10000)])});if(!r.data?.some(m=>m.id===model))throw failure('WORKER_UNREACHABLE');return;}catch(e){if(i===attempts-1)throw failure('WORKER_UNREACHABLE',e);await require('node:timers/promises').setTimeout(delay,null,{signal:this.lifecycle.signal});}}},
 async verifyWorker(){const node=this.node();if(!node||!this.registeredGateway)throw failure('REGISTRATION_EXPIRED');try{const r=await json(this.registeredGateway+'/nodes/'+encodeURIComponent(node.id)+'/health',{method:'POST',headers:gatewayHeaders({'X-Common-Node-Token':node.node_token}),signal:AbortSignal.timeout(15000)});if(r.healthy!==true)throw failure('WORKER_UNREACHABLE');this.workerVerified=true;this.lastVerified=Date.now();return r;}catch(e){this.workerVerified=false;throw failure(e.status===404||e.status===401?'REGISTRATION_EXPIRED':'WORKER_UNREACHABLE',e);}},
 async retryNow(){// Respect a provider's rate-limit cooldown, even for manual retries.
  if(this.lastError?.code==='TUNNEL_RATE_LIMITED'&&Date.now()<this.retryAfter)throw failure('TUNNEL_RATE_LIMITED');this.retryAfter=0;this.lastVerified=0;await this.refresh();return this.reconcile();},
 async testSetup({target='network',contributor=this.settings.value.role!=='chat'}={}){if(!['local','network'].includes(target)||typeof contributor!=='boolean')throw new Error('Invalid test path.');if(this.testing)throw new Error('A setup test is already running.');this.testing=true;this.state.setupTest={running:true,ready:false,contributor,target,stages:STAGES.map(stage=>({stage,status:'pending'}))};this.record('setup_started');this.emitState();const run=async(stage,fn)=>{const entry=this.state.setupTest.stages.find(x=>x.stage===stage);entry.status='running';this.emitState();const start=Date.now();try{await fn();entry.status='passed';}catch(e){entry.status='failed';entry.code=classify(e,({registration:'REGISTRATION_FAILED',gateway:'GATEWAY_UNREACHABLE',network:'GATEWAY_UNREACHABLE',publicEndpoint:'WORKER_UNREACHABLE',worker:'WORKER_UNREACHABLE'})[stage]||'UNKNOWN');entry.error=require('./errors.cjs').HELP[entry.code];entry.httpStatus=e.status;throw e;}finally{entry.durationMs=Date.now()-start;this.emitState();}};const skip=stage=>{this.state.setupTest.stages.find(x=>x.stage===stage).status='skipped';};
 try{await this.serial(async()=>{
  await run('application',async()=>{});
  if(target==='network'||contributor){await run('network',async()=>{try{await Promise.race([dns.lookup(new URL(this.settings.value.gateway).hostname),new Promise((_,reject)=>{const t=setTimeout(()=>reject(failure('GATEWAY_UNREACHABLE')),5000);t.unref();})]);}catch(e){throw failure('GATEWAY_UNREACHABLE',e);}});await run('gateway',async()=>{await this.refreshGateway();if(!this.state.gateway.online)throw failure('GATEWAY_UNREACHABLE');});}else{skip('network');skip('gateway');}
  if(target==='local'||contributor){await run('ollama',async()=>{await this.refresh();if(!this.state.ollama.online)await this.startOllama();});await run('model',async()=>{if(!this.state.ollama.models.some(m=>m.name===this.settings.value.model||m.name===this.settings.value.model+':latest'))throw failure('MODEL_NOT_INSTALLED');});await run('localInference',()=>this.modelHealth());}else for(const s of ['ollama','model','localInference'])skip(s);
  if(contributor){await run('helper',async()=>{if(!this.helperInstalled())throw failure('TUNNEL_START_FAILED');});await this.stopWorker();this.testStage=run;try{await this.startWorker();}finally{this.testStage=null;}}
  else for(const s of ['helper','publicEndpoint','registration','worker'])skip(s);
  if(target==='network'||contributor)await run('networkInference',async()=>{try{await streamChat(this.settings.value.gateway+'/v1/chat/completions',gatewayHeaders(this.token()?{'X-Common-Node-Token':this.token()}:{}),{model:'auto',messages:[{role:'user',content:'Reply with OK.'}],max_tokens:8},AbortSignal.any([this.lifecycle.signal,AbortSignal.timeout(120000)]),()=>{});}catch(e){throw failure(classify(e,'INFERENCE_FAILED'),e);}});else skip('networkInference');
  if(target==='network'||contributor)this.networkVerified=true;this.state.setupTest.ready=true;this.record('setup_completed');
 });}catch(e){this.record('setup_failed',errorFields(e));if(!this.state.setupTest.stages.some(s=>s.status==='failed')){const entry=this.state.setupTest.stages.find(s=>s.status==='pending');if(entry){entry.status='failed';entry.code=classify(e);entry.error=require('./errors.cjs').HELP[entry.code];}}for(const s of this.state.setupTest.stages)if(s.status==='pending')s.status='skipped';}finally{if(contributor&&!this.settings.value.contributing)await this.serial(()=>this.stopWorker({preserveRegistration:this.state.setupTest.ready}));this.testing=false;this.state.setupTest.running=false;this.emitState();}return this.state.setupTest;
 },
 async refreshOverview(){try{const r=await json(this.settings.value.gateway+'/network/overview',{headers:gatewayHeaders(),signal:AbortSignal.timeout(5000)});if(!Number.isInteger(r.contributors)||!Number.isInteger(r.endpoints)||r.contributors<0||r.endpoints<0)throw new Error('Malformed overview');this.state.overview={contributors:r.contributors,endpoints:r.endpoints,checkedAt:Date.now()};}catch{this.state.overview=null;}},
};
module.exports={methods,STAGES};
