const {app,BrowserWindow,ipcMain,Tray,Menu,nativeImage,powerMonitor,shell,dialog,safeStorage,clipboard,Notification}=require('electron'),path=require('node:path'),{pathToFileURL}=require('node:url');
const fs=require('node:fs');const {Diagnostics}=require('./diagnostics.cjs'),{classify,HELP,errorFields}=require('./errors.cjs'),{createUpdates}=require('./updater.cjs');
const {Settings}=require('./settings.cjs'),{Service}=require('./service.cjs');let win,tray,service,settings,quitting=false,suspended=false,interval,updates,diagnostics;const page=path.join(__dirname,'../renderer/index.html'),profile=app.commandLine.getSwitchValue('user-data-dir');if(profile)app.setPath('userData',path.resolve(profile));
if(!app.requestSingleInstanceLock())app.quit();else{
 app.on('second-instance',()=>{win?.show();win?.focus();});
 app.whenReady().then(async()=>{
  let build;try{build=JSON.parse(fs.readFileSync(path.join(__dirname,'build-info.json'),'utf8')).commit;}catch{}diagnostics=new Diagnostics(app.getPath('userData'),{version:app.getVersion(),build});
  try{settings=new Settings(app.getPath('userData'),{secureStorage:safeStorage});}catch(e){dialog.showErrorBox('Common settings',e.message);app.quit();return;}
  service=new Service(settings,{dataDir:app.getPath('userData'),diagnostics,openPath:p=>shell.openPath(p),power:()=>({battery:powerMonitor.isOnBatteryPower(),idleSeconds:powerMonitor.getSystemIdleTime(),suspended})});
  const shared=service.identity.forGateway(settings.value.gateway);if(shared&&!settings.value.identities[settings.value.gateway]){settings.value.identities[settings.value.gateway]={id:shared.node_id,node_token:shared.node_token,name:shared.name};settings.save();service.identity.clear(settings.value.gateway);}
  win=new BrowserWindow({width:1240,height:850,minWidth:820,minHeight:640,backgroundColor:'#282624',title:'Common',show:false,icon:path.join(__dirname,'../../assets/icon.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.webContents.on('render-process-gone',(_e,details)=>{service.record('renderer_failed',{code:'APP_CRASHED'});service.diagnostics.unexpectedExit=true;win.reload();});win.loadFile(page);win.setMenuBarVisibility(false);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.session.setPermissionRequestHandler((_c,_p,cb)=>cb(false));
  win.once('ready-to-show',()=>{const loginLaunch=process.argv.includes('--hidden')||(process.platform==='darwin'&&app.getLoginItemSettings().wasOpenedAtLogin);if(!loginLaunch||!settings.value.setupComplete||!tray)win.show();});
  win.on('close',e=>{if(!quitting){e.preventDefault();if(settings.value.closeToTray&&tray)win.hide();else app.quit();}});
  try{tray=new Tray(nativeImage.createFromPath(path.join(__dirname,'../../assets/tray.png')));tray.setToolTip('Common');tray.on('click',()=>win.show());}catch{tray=null;}
  const normalIcon=nativeImage.createFromPath(path.join(__dirname,'../../assets/tray.png'));const pixels=Buffer.from(normalIcon.toBitmap());for(let i=0;i<pixels.length;i+=4)if(pixels[i+3]){pixels[i]=50;pixels[i+1]=155;pixels[i+2]=235;}const attentionIcon=pixels.length?nativeImage.createFromBitmap(pixels,normalIcon.getSize()):normalIcon;
  const show=tab=>{win.show();win.webContents.send('common:navigate',tab);};
  const menu=()=>{if(!tray)return;const h=service.health(),attention=!!service.lastError;tray.setImage(attention?attentionIcon:normalIcon);tray.setToolTip(attention?'Common needs attention':service.state.worker.status);tray.setContextMenu(Menu.buildFromTemplate([{label:'Common',enabled:false},{label:service.state.worker.status+' · '+settings.value.model,enabled:false},{type:'separator'},{label:'Open Common',click:()=>show('chat')},{label:settings.value.contributing?'Pause contribution':'Resume contribution',enabled:settings.value.setupComplete,click:()=>service.update({contributing:!settings.value.contributing}).catch(e=>dialog.showErrorBox('Contribution',HELP[classify(e)]))},{label:'Test connection',click:()=>{show('diagnostics');service.testSetup().catch(()=>{});}},{label:'Open diagnostics',click:()=>show('diagnostics')},{label:'Retry now',click:()=>service.retryNow().catch(()=>{})},{label:'Settings',click:()=>show('settings')},{label:'Quit',click:()=>app.quit()}]));};
  let notifiedCode=null;service.on('state',()=>{const code=service.lastError?.code;if(code&&code!==notifiedCode&&Notification.isSupported()){notifiedCode=code;new Notification({title:'Common needs attention',body:HELP[code]||HELP.UNKNOWN}).show();}if(!code)notifiedCode=null;});

  let emitTimer;service.on('state',()=>{if(emitTimer)return;emitTimer=setTimeout(()=>{emitTimer=null;if(!win.isDestroyed())win.webContents.send('common:state',service.snapshot());menu();},100);});service.on('chat-delta',d=>{if(!win.isDestroyed())win.webContents.send('common:chat-delta',d);});
  const handlers={report:p=>service.reporting.report(p),testSetup:p=>service.testSetup(p),retryNow:()=>service.retryNow(),benchmark:()=>service.serial(()=>service.modelHealth({benchmark:true})),copyDiagnostics:()=>clipboard.writeText(JSON.stringify(service.diagnosticReport(),null,2)),exportDiagnostics:async()=>{const result=await dialog.showSaveDialog(win,{defaultPath:'Common-diagnostics.json',filters:[{name:'JSON report',extensions:['json']}]});if(!result.canceled&&result.filePath)fs.writeFileSync(result.filePath,JSON.stringify(service.diagnosticReport(),null,2),{mode:0o600});},checkUpdates:()=>updates.check(),installUpdate:()=>updates.install(),rendererError:()=>{service.record('renderer_failed',{code:'APP_CRASHED'});},snapshot:()=>service.snapshot(),refresh:async()=>{await service.refresh();return service.snapshot();},catalogue:()=>service.catalogue(),update:async p=>{if('startAtLogin'in p){if(process.platform==='linux'&&p.startAtLogin)throw new Error('Start at login is not available on Linux in this release.');app.setLoginItemSettings({openAtLogin:!!p.startAtLogin,path:process.env.PORTABLE_EXECUTABLE_FILE||process.execPath,args:app.isPackaged?['--hidden']:[app.getAppPath(),'--hidden']});}return service.update(p);},installOllama:()=>service.installOllama(),startOllama:()=>service.startOllama(),prepareTunnel:()=>service.prepareTunnel(),pullModel:()=>service.pullModel(),cancelDownload:()=>service.cancelDownload(),chat:d=>service.chat(d),cancelChat:()=>service.cancelChat(),hide:()=>tray?win.hide():win.minimize(),quit:()=>app.quit(),openHelp:topic=>{const urls={ollama:'https://ollama.com/download',linux:'https://docs.ollama.com/linux',models:'https://ollama.com/library',common:'https://commonai.com.au',source:'https://github.com/TheCommonAI/common-desktop'};if(!urls[topic])throw new Error('Unknown help page.');return shell.openExternal(urls[topic]);},openLink:target=>{let url;try{url=new URL(String(target));}catch{throw new Error('That link could not be read.');}if(url.protocol!=='https:'&&url.protocol!=='http:')throw new Error('Only web links can be opened.');return shell.openExternal(url.href);}};
  for(const [name,fn]of Object.entries(handlers))ipcMain.handle('common:'+name,async(event,payload)=>{if(event.sender!==win.webContents||event.senderFrame?.url!==pathToFileURL(page).href)throw new Error('Invalid application context.');try{return {ok:true,value:await fn(payload)};}catch(e){const code=classify(e);service.record('setup_failed',errorFields(e));return {ok:false,error:HELP[code]||HELP.UNKNOWN,code};}});
  powerMonitor.on('suspend',()=>{suspended=true;service.worker?.pause();service.reconcile().catch(()=>{});});powerMonitor.on('resume',()=>{suspended=false;service.retryAfter=0;service.lastVerified=0;service.refresh().then(()=>service.reconcile()).catch(()=>{});});for(const event of ['on-battery','on-ac'])powerMonitor.on(event,()=>service.reconcile().catch(()=>{}));updates=createUpdates(app,service);await service.refresh();service.refreshOverview().catch(()=>{});service.catalogue().catch(()=>{});if(settings.value.setupComplete&&!settings.value.contributing)service.testSetup({target:settings.value.chatTarget,contributor:false}).catch(()=>{});await service.reconcile();menu();interval=setInterval(()=>{service.refresh().catch(()=>{});service.reconcile().catch(()=>{});},5000);
 }).catch(e=>{dialog.showErrorBox('Common could not start',e.message);app.exit(1);});
 app.on('activate',()=>win?.show());app.on('window-all-closed',()=>{if(!tray)app.quit();});app.on('before-quit',e=>{if(quitting)return;quitting=true;e.preventDefault();clearInterval(interval);updates?.close();const deadline=setTimeout(()=>{service?.tunnel?.kill();service?.ownedOllama?.kill();app.exit(0);},8000);Promise.resolve(service?.close()).finally(()=>{clearTimeout(deadline);tray?.destroy();app.quit();});});
}

process.on('uncaughtException',e=>{try{diagnostics?.record('app_crashed',errorFields(e,'APP_CRASHED'));}finally{app.exit(1);}});
process.on('unhandledRejection',e=>{diagnostics?.record('app_crashed',errorFields(e,'APP_CRASHED'));});
