const {app,BrowserWindow,ipcMain,Tray,Menu,nativeImage,powerMonitor,shell,dialog}=require('electron'),path=require('node:path'),{pathToFileURL}=require('node:url');
const {Settings}=require('./settings.cjs'),{Service}=require('./service.cjs');let win,tray,service,settings,quitting=false,suspended=false,interval;const page=path.join(__dirname,'../renderer/index.html'),profile=app.commandLine.getSwitchValue('user-data-dir');if(profile)app.setPath('userData',path.resolve(profile));
if(!app.requestSingleInstanceLock())app.quit();else{
 app.on('second-instance',()=>{win?.show();win?.focus();});
 app.whenReady().then(async()=>{
  try{settings=new Settings(app.getPath('userData'));}catch(e){dialog.showErrorBox('Common settings',e.message);app.quit();return;}
  service=new Service(settings,{dataDir:app.getPath('userData'),openPath:p=>shell.openPath(p),power:()=>({battery:powerMonitor.isOnBatteryPower(),idleSeconds:powerMonitor.getSystemIdleTime(),suspended})});
  win=new BrowserWindow({width:1240,height:850,minWidth:820,minHeight:640,backgroundColor:'#282624',title:'Common',show:false,icon:path.join(__dirname,'../../assets/icon.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.loadFile(page);win.setMenuBarVisibility(false);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.session.setPermissionRequestHandler((_c,_p,cb)=>cb(false));
  win.once('ready-to-show',()=>{const loginLaunch=process.argv.includes('--hidden')||(process.platform==='darwin'&&app.getLoginItemSettings().wasOpenedAtLogin);if(!loginLaunch||!settings.value.setupComplete)win.show();});
  win.on('close',e=>{if(!quitting){e.preventDefault();if(settings.value.closeToTray&&tray)win.hide();else app.quit();}});
  try{tray=new Tray(nativeImage.createFromPath(path.join(__dirname,'../../assets/tray.png')));tray.setToolTip('Common');tray.on('click',()=>win.show());}catch{tray=null;}
  const menu=()=>tray?.setContextMenu(Menu.buildFromTemplate([{label:'Open Common',click:()=>win.show()},{label:service.state.worker.status,enabled:false},{type:'separator'},{label:settings.value.contributing?'Pause contribution':'Resume contribution',enabled:settings.value.setupComplete,click:()=>service.update({contributing:!settings.value.contributing}).catch(e=>dialog.showErrorBox('Contribution',e.message))},{label:'Quit Common',click:()=>app.quit()}]));
  let emitTimer;service.on('state',()=>{if(emitTimer)return;emitTimer=setTimeout(()=>{emitTimer=null;if(!win.isDestroyed())win.webContents.send('common:state',service.snapshot());menu();},100);});service.on('chat-delta',d=>{if(!win.isDestroyed())win.webContents.send('common:chat-delta',d);});
  const handlers={snapshot:()=>service.snapshot(),refresh:async()=>{await service.refresh();return service.snapshot();},catalogue:()=>service.catalogue(),update:async p=>{if('startAtLogin'in p){if(process.platform==='linux'&&p.startAtLogin)throw new Error('Start at login is not available on Linux in this release.');app.setLoginItemSettings({openAtLogin:!!p.startAtLogin,path:process.env.PORTABLE_EXECUTABLE_FILE||process.execPath,args:app.isPackaged?['--hidden']:[app.getAppPath(),'--hidden']});}return service.update(p);},installOllama:()=>service.installOllama(),startOllama:()=>service.startOllama(),prepareTunnel:()=>service.prepareTunnel(),pullModel:()=>service.pullModel(),cancelDownload:()=>service.cancelDownload(),chat:d=>service.chat(d),cancelChat:()=>service.cancelChat(),hide:()=>tray?win.hide():win.minimize(),quit:()=>app.quit(),openHelp:topic=>{const urls={ollama:'https://ollama.com/download',linux:'https://docs.ollama.com/linux',models:'https://ollama.com/library',common:'https://commonai.com.au',source:'https://github.com/TheCommonAI/common-desktop'};if(!urls[topic])throw new Error('Unknown help page.');return shell.openExternal(urls[topic]);},openLink:target=>{let url;try{url=new URL(String(target));}catch{throw new Error('That link could not be read.');}if(url.protocol!=='https:'&&url.protocol!=='http:')throw new Error('Only web links can be opened.');return shell.openExternal(url.href);}};
  for(const [name,fn]of Object.entries(handlers))ipcMain.handle('common:'+name,async(event,payload)=>{if(event.sender!==win.webContents||event.senderFrame?.url!==pathToFileURL(page).href)throw new Error('Invalid application context.');try{return {ok:true,value:await fn(payload)};}catch(e){return {ok:false,error:e.message||'This action could not be completed.'};}});
  powerMonitor.on('suspend',()=>{suspended=true;service.worker?.pause();service.reconcile().catch(()=>{});});powerMonitor.on('resume',()=>{suspended=false;service.reconcile().catch(()=>{});});for(const event of ['on-battery','on-ac'])powerMonitor.on(event,()=>service.reconcile().catch(()=>{}));await service.refresh();service.catalogue().catch(()=>{});await service.reconcile();menu();interval=setInterval(()=>{service.refresh().catch(()=>{});service.reconcile().catch(()=>{});},5000);
 }).catch(e=>{dialog.showErrorBox('Common could not start',e.message);app.exit(1);});
 app.on('activate',()=>win?.show());app.on('window-all-closed',()=>{if(!tray)app.quit();});app.on('before-quit',e=>{if(quitting)return;quitting=true;e.preventDefault();clearInterval(interval);const deadline=setTimeout(()=>{service?.tunnel?.kill();service?.ownedOllama?.kill();app.exit(0);},8000);Promise.resolve(service?.close()).finally(()=>{clearTimeout(deadline);tray?.destroy();app.quit();});});
}
