const {EventEmitter}=require('node:events'),os=require('node:os'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{randomBytes}=require('node:crypto');
const {json,checkedFetch,lines,streamChat,gatewayHeaders,CLIENT}=require('./http.cjs'),{createWorker}=require('./worker.cjs'),{download,installTunnel}=require('./downloads.cjs'),identityStore=require('./identity.cjs');
const {Diagnostics}=require('./diagnostics.cjs'),{Reporting}=require('./observability.cjs'),{failure,classify,errorFields}=require('./errors.cjs');
const OLLAMA='http://127.0.0.1:11434';
const FALLBACK_MODELS=[{tag:'llama3.2:3b',name:'Llama 3.2 · 3B',description:'A compact general model for everyday chat.',minRam:6,estimate:'About 2 GB'},{tag:'qwen3:8b',name:'Qwen 3 · 8B',description:'A larger general model for computers with more memory.',minRam:12,estimate:'About 5.2 GB'}];
// cloudflared says why it is quitting before it goes, and the reasons want
// different answers: a rate-limited quick tunnel needs a wait, a refused
// connection needs a look at the network. "Try again" is only right for one of
// them, so carry its own last line into the status the user reads.
//
// Not every fatal line is a levelled one -- the rate-limit refusal prints as a
// bare "quick tunnel provisioning failed with status 429: error code: 1015"
// with no timestamp or ERR at all. So drop the chatter and keep the last line
// standing, rather than looking for a level that may not be there.
// Retrying a rate limit every 30 seconds is how you keep one: each attempt is
// another request to the API that is refusing them, so the window never gets a
// quiet moment to age out. A helper that quit for this reason waits ten
// minutes; every other reason keeps the ordinary cadence.
const RATE_LIMITED=/\b(?:429|1015)\b/;
function helperExit(output){const line=output.split(/\r?\n/).map(l=>l.trim()).filter(l=>l&&!/^\S+\s+(?:INF|DBG)\s|^[|+\-\s]*$/.test(l)).pop(),reason=line?line.replace(/^\S+\s+(?:ERR|WRN|FTL)\s+/,'').replace(/\s+/g,' ').trim():'';if(RATE_LIMITED.test(reason))return {message:'Cloudflare is rate-limiting new connections from this network. Waiting ten minutes before trying again.',retryAfter:600000};if(!reason)return {message:'The connection helper exited. Try again.'};return {message:'The connection helper exited: '+(reason.length>200?reason.slice(0,200)+'…':reason)};}
function policy(s,{battery,idleSeconds,suspended=false}){if(!s.contributing)return 'Paused';if(suspended)return 'Computer asleep';if(s.pauseBattery&&battery)return 'Paused on battery';if(s.idleOnly&&idleSeconds<s.idleMinutes*60)return 'Waiting until your computer is idle';return null;}
class Service extends EventEmitter{
 constructor(settings,{dataDir,openPath,power=()=>({battery:false,idleSeconds:0}),ollama=OLLAMA,spawnTunnel=spawn,spawnOllama=spawn,ollamaAttempts=20,ollamaDelay=500,identity=identityStore,diagnostics=null}){super();Object.assign(this,{settings,dataDir,openPath,power,ollama,spawnTunnel,spawnOllama,ollamaAttempts,ollamaDelay,identity});this.state={ollama:{online:false,models:[],running:[]},gateway:{online:false},worker:{status:'Paused',active:0,completed:0,failed:0,bytes:0},download:null,models:FALLBACK_MODELS,hardware:{},chatBusy:false};this.tail=Promise.resolve();this.closed=false;this.lifecycle=new AbortController();this.lastRefresh=0;this.diagnostics=diagnostics||new Diagnostics(dataDir);this.reporting=new Reporting(this);this.diagnostics.onEvent=e=>this.reporting.enqueue({...e,platform:process.platform,arch:process.arch,cores:Math.ceil(os.cpus().length/4)*4,ramGB:Math.ceil(os.totalmem()/1024**3/8)*8,model:this.settings.value.model});this.reporting.enqueue(this.diagnostics.data.events.at(-1));this.retries=0;if(this.diagnostics.unexpectedExit)this.record('app_crashed',{code:'APP_CRASHED'});}
 snapshot(){const node=this.node();return {...this.state,version:this.diagnostics.version,build:this.diagnostics.build,health:this.health(),chatReady:{local:this.state.ollama.online&&this.modelHealthy===this.modelKey(),network:!!this.networkVerified&&this.state.gateway.online},diagnostics:this.diagnosticReport(),statistics:this.diagnostics.stats(),activity:this.diagnostics.data.activity,benchmark:this.diagnostics.data.benchmark,unexpectedExit:this.diagnostics.unexpectedExit,lastError:this.lastError,settings:{...this.settings.public(),name:this.nodeName(),nodeId:node?.id||null},power:this.power()};}
 emitState(){this.emit('state',this.snapshot());}
 serial(fn){const r=this.tail.then(fn);this.tail=r.catch(()=>{});return r;}
 async refresh(){if(!this.refreshPromise)this.refreshPromise=this.refreshInternal().finally(()=>{this.refreshPromise=null;});return this.refreshPromise;}
 async refreshInternal(){if(this.refreshing)return;this.refreshing=true;try{const cpu=os.cpus(),sum=cpu.reduce((a,c)=>{a.idle+=c.times.idle;a.total+=Object.values(c.times).reduce((x,y)=>x+y,0);return a;},{idle:0,total:0});const cpuPercent=this.lastCpu&&sum.total!==this.lastCpu.total?Math.round(100*(1-(sum.idle-this.lastCpu.idle)/(sum.total-this.lastCpu.total))):null;this.lastCpu=sum;let disk=null;try{const i=fs.statfsSync(os.homedir());disk=i.bavail*i.bsize;}catch{}this.state.hardware={platform:process.platform,arch:process.arch,os:os.release(),cpu:cpu[0]?.model||'Unavailable',cores:cpu.length,cpuPercent,ram:os.totalmem(),freeRam:os.freemem(),freeDisk:disk,appMemory:process.memoryUsage().rss};const [models,version,running]=await Promise.allSettled(['/api/tags','/api/version','/api/ps'].map(p=>json(this.ollama+p,{signal:AbortSignal.timeout(2500)})));const wasOnline=this.state.ollama.online;this.state.ollama={online:models.status==='fulfilled',models:models.status==='fulfilled'?models.value.models||[]:[],version:version.status==='fulfilled'?version.value.version:null,running:running.status==='fulfilled'?running.value.models||[]:[]};if(this.state.ollama.online&&!wasOnline)this.record('ollama_detected');if(!this.state.ollama.online)this.modelHealthy=null;this.diagnostics.tick(this.state.worker.status==='Contributing');this.reporting.flush().catch(()=>{});if(Date.now()-this.lastRefresh>30000){this.lastRefresh=Date.now();await this.refreshGateway();this.refreshOverview().catch(()=>{});}this.emitState();}finally{this.refreshing=false;}}
 async refreshGateway(){const g=this.settings.value.gateway;try{const r=await json(g+'/health',{headers:gatewayHeaders(),signal:AbortSignal.timeout(5000)});if(r.status!=='ok')throw failure('GATEWAY_MALFORMED');if(this.settings.value.gateway===g){if(!this.state.gateway.online)this.record('gateway_reachable');this.state.gateway={online:true,checkedAt:Date.now()};}}catch(e){if(this.settings.value.gateway===g){if(this.state.gateway.online)this.record('gateway_unreachable',errorFields(e,'GATEWAY_UNREACHABLE'));this.networkVerified=false;this.state.gateway={online:false,checkedAt:Date.now(),code:classify(e,'GATEWAY_UNREACHABLE')};}}}
 async catalogue(){try{const items=await json(this.settings.value.gateway+'/catalogue',{headers:gatewayHeaders(),signal:AbortSignal.timeout(5000)}),models=items.filter(m=>typeof m.source==='string'&&m.source.startsWith('ollama:')).map(m=>({tag:m.source.slice(7),name:m.display_name,description:m.capability_text,minRam:m.min_ram_gb||0,needsGpu:!!m.needs_gpu,minVram:m.min_vram_gb||0,catalogueId:m.id,domains:m.domain_tags,estimate:'Size shown during download'}));this.state.models=[...FALLBACK_MODELS,...models.filter(m=>!FALLBACK_MODELS.some(f=>f.tag===m.tag))];}catch{this.state.models=FALLBACK_MODELS;}this.emitState();return this.state.models;}
 async startOllama(){if(this.state.ollama.online)return;let found=false;const candidates=process.platform==='win32'?[path.join(process.env.LOCALAPPDATA||os.homedir(),'Programs','Ollama','ollama.exe'),'ollama.exe']:process.platform==='darwin'?['/Applications/Ollama.app/Contents/Resources/ollama','/usr/local/bin/ollama','/opt/homebrew/bin/ollama','ollama']:['/usr/local/bin/ollama','/usr/bin/ollama','ollama'];for(const command of candidates){if(path.isAbsolute(command)&&!fs.existsSync(command))continue;const child=this.spawnOllama(command,['serve'],{windowsHide:true,stdio:'ignore',env:{...process.env,OLLAMA_HOST:'127.0.0.1:11434'}}),started=await new Promise(r=>{child.once('error',()=>r(false));child.once('spawn',()=>r(true));});if(!started)continue;found=true;this.ownedOllama=child;child.on('exit',()=>{if(this.ownedOllama===child)this.ownedOllama=null;});for(let i=0;i<this.ollamaAttempts;i++){await require('node:timers/promises').setTimeout(this.ollamaDelay,null,{signal:this.lifecycle.signal});await this.refresh();if(this.state.ollama.online)return;}break;}const e=failure(found?'OLLAMA_NOT_RUNNING':'OLLAMA_NOT_INSTALLED');this.record('ollama_start_failed',errorFields(e));throw e;}
 async task(label,fn){if(this.downloadController)throw new Error('A download is already in progress.');const c=new AbortController();this.downloadController=c;this.state.download={label,status:'Starting',completed:0,total:null};this.emitState();const onProgress=p=>{this.state.download={...this.state.download,...p};this.emitState();};try{const result=await fn({signal:c.signal,onProgress});this.state.download={...this.state.download,status:'Complete',done:true};return result;}catch(e){this.state.download={...this.state.download,status:c.signal.aborted?'Paused — choose Download to resume':'Download failed',error:c.signal.aborted?null:e.message,done:true};if(!c.signal.aborted)throw e;}finally{this.downloadController=null;this.emitState();}}
 cancelDownload(){this.downloadController?.abort();}
 async installOllama(){if(process.platform==='linux')throw new Error('Use the Linux installation guide, then choose Check again.');const name=process.platform==='win32'?'OllamaSetup.exe':'Ollama.dmg';return this.task('Ollama installer',async options=>{const destination=path.join(this.dataDir,'downloads',name);await download('https://ollama.com/download/'+name,destination,options);options.signal.throwIfAborted();const error=await this.openPath(destination);if(error)throw new Error('Could not open the installer: '+error);});}
 prepareTunnel(){if(this.helperInstalled())return Promise.resolve(path.join(this.dataDir,'bin',process.platform==='win32'?'cloudflared.exe':'cloudflared'));return this.task('Common connection helper',o=>installTunnel(path.join(this.dataDir,'bin'),o));}
 async pullModel(){const model=this.settings.value.model;return this.task(model,async({signal,onProgress})=>{const r=await checkedFetch(this.ollama+'/api/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,stream:true}),signal});for await(const line of lines(r.body)){if(!line)continue;const item=JSON.parse(line);if(item.error)throw new Error('Ollama could not download this model. Check disk space and the model tag, then retry.');onProgress({status:item.status,completed:item.completed||0,total:item.total||null});}await this.refresh();if(!this.state.ollama.models.some(m=>m.name===model||m.name===model+':latest'))throw new Error('Ollama did not finish installing the model. Retry the download.');});}
 update(patch){return this.serial(async()=>{if(('gateway'in patch&&patch.gateway!==this.settings.value.gateway)||('model'in patch&&patch.model!==this.settings.value.model)||('concurrency'in patch&&patch.concurrency!==this.settings.value.concurrency))await this.stopWorker();if(patch.setupComplete===true&&(!this.state.setupTest?.ready||['gateway','model','chatToken'].some(k=>k in patch)||patch.contributing===true&&!this.state.setupTest.contributor))throw new Error('Run Test my setup successfully before completing setup.');if('gateway'in patch&&patch.gateway!==this.settings.value.gateway)patch={...patch,telemetry:false};this.settings.update(patch);if(['gateway','model','chatToken'].some(k=>k in patch)){this.state.setupTest=null;this.networkVerified=false;this.modelHealthy=null;}if(patch.telemetry===false)this.reporting.clear();this.lastRefresh=0;this.retryAfter=0;await this.reconcileInternal();this.emitState();return this.snapshot();});}
 // The node this machine is on the network, wherever it joined from: the file
 // the terminal client writes comes first, so a machine that ran `common join`
 // keeps one name and one node_token when it opens the app.
 node(gateway=this.settings.value.gateway){const own=this.settings.value.identities[gateway];if(own)return {...own,name:own.name||this.settings.value.name};const shared=this.identity.forGateway(gateway);return shared?{id:shared.node_id,node_token:shared.node_token,name:shared.name}:null;}
 nodeName(){return this.node()?.name||this.settings.value.name;}
 rememberNode(gateway,{id,node_token,name,catalogue_id=null,domain_tags=null}){this.settings.value.identities[gateway]={id,node_token,name};this.settings.save();this.identity.clear(gateway);}
 forgetNode(gateway){delete this.settings.value.identities[gateway];this.settings.save();this.identity.clear(gateway);}
 token(){const s=this.settings.value;return s.chatTokens[s.gateway]||this.node()?.node_token;}
 async chat({messages,target}){
  if(this.chatController)throw new Error('Wait for this answer or stop it first.');
  if(!['local','network'].includes(target))throw new Error('Choose where to send your message.');
  if(!Array.isArray(messages)||!messages.length||messages.length>100||messages.some(m=>!['user','assistant'].includes(m.role)||typeof m.content!=='string')||JSON.stringify(messages).length>512000)throw new Error('This conversation is too long. Start a new chat.');
  let firstToken=false;const started=Date.now();this.record('chat_started',{target,model:this.settings.value.model});const c=new AbortController();this.chatController=c;this.chatCancelled=false;this.state.chatBusy=true;this.emitState();
  const timer=setTimeout(()=>c.abort(),300000),s=this.settings.value,gateway=s.gateway,model=s.model;
  const send=async()=>{const token=this.token();const result=await streamChat(target==='local'?this.ollama+'/v1/chat/completions':gateway+'/v1/chat/completions',target==='network'?gatewayHeaders(token?{'X-Common-Node-Token':token}:{}):{},{model:target==='local'?model:'auto',messages},c.signal,d=>{if(!firstToken){firstToken=true;this.record('first_token',{ttftMs:Date.now()-started,target,model});}this.emit('chat-delta',d);});if(target==='network')this.networkVerified=true;this.lastPerformance=result.receipt.performance;this.record('chat_completed',{...this.lastPerformance,target});return result;};
  try{
   try{return await send();}catch(e){
    // Retry only a recognised gateway rejection BEFORE inference. Never replay
    // a prompt after a worker rejection or use a different gateway.
    if(target!=='network'||e.status!==401||e.code!=='registration_expired'||this.settings.value.chatTokens[gateway]||this.registeredGateway!==gateway||policy(this.settings.value,this.power())||c.signal.aborted)throw e;
    await this.serial(async()=>{
     if(this.settings.value.gateway!==gateway||c.signal.aborted||policy(this.settings.value,this.power()))throw e;
     await this.stopWorker();
     try{await this.startWorker();}catch(reconnectError){await this.stopWorker();throw reconnectError;}
    });
    if(this.settings.value.gateway!==gateway||c.signal.aborted)throw e;
    return await send();
   }
  }catch(e){
   this.record('chat_failed',{...errorFields(e,c.signal.aborted?'INFERENCE_CANCELLED':'INFERENCE_FAILED'),durationMs:Date.now()-started,target});if(target==='network'){this.state.gateway.chatError={status:e.status||null,code:e.code||'connection_error',origin:e.origin||'unknown'};this.emitState();}
   if(c.signal.aborted)throw failure(this.chatCancelled?'INFERENCE_CANCELLED':'INFERENCE_TIMEOUT',e);throw failure(classify(e,'INFERENCE_FAILED'),e);
  }finally{clearTimeout(timer);this.chatController=null;this.state.chatBusy=false;this.emitState();}
 }
 cancelChat(){this.chatCancelled=true;this.chatController?.abort();}
 reconcile(){return this.serial(()=>this.reconcileInternal());}
 async reconcileInternal(){if(this.closed||this.testing)return;const reason=policy(this.settings.value,this.power());if(reason){this.lastError=null;if(this.worker){this.record('contribution_paused');await this.stopWorker({preserveRegistration:true});}this.state.worker.status=reason;this.emitState();return;}if(this.retryAfter&&Date.now()<this.retryAfter)return;
 try{if(this.worker&&this.tunnel&&!this.tunnel.killed&&this.tunnel.exitCode===null&&this.state.ollama.online&&this.modelHealthy===this.modelKey()){if(Date.now()-(this.lastVerified||0)>30000){try{await this.verifyWorker();return;}catch(e){if(e.code!=='REGISTRATION_EXPIRED')throw e;await this.stopWorker();}}else return;}if(this.worker)await this.stopWorker();this.record('worker_reconnecting');await this.startWorker();this.retries=0;this.retryAfter=0;this.lastError=null;}
 catch(e){await this.stopWorker();const code=classify(e,'REGISTRATION_FAILED');this.lastCause=e;this.lastError={code};this.state.worker.status=require('./errors.cjs').HELP[code];this.record('registration_failed',errorFields(e,code));this.retryAfter=Date.now()+(code==='TUNNEL_RATE_LIMITED'?600000:Math.min(300000,5000*2**Math.min(6,this.retries++)))*(1+Math.random()*0.2);this.emitState();}}

 async startWorker(){if(!this.state.ollama.online)await this.startOllama();const s=this.settings.value;if(!this.state.ollama.models.some(m=>m.name===s.model||m.name===s.model+':latest'))throw failure('MODEL_NOT_INSTALLED');await this.modelHealth();const executable=path.join(this.dataDir,'bin',process.platform==='win32'?'cloudflared.exe':'cloudflared');if(!fs.existsSync(executable))throw failure('TUNNEL_START_FAILED');this.state.worker.status='Connecting';this.emitState();const token=randomBytes(24).toString('base64url');this.worker=await createWorker({model:s.model,token,ollama:this.ollama,limit:s.concurrency,onEvent:(event,fields)=>this.record(event,fields),onJob:m=>{m.workerId=this.diagnostics.data.installationId;if(!m.success)this.modelHealthy=null;this.diagnostics.job(m);this.lastPerformance=m;},onStats:stats=>{this.state.worker={...this.state.worker,...stats};this.emitState();}});const stage=this.testStage||((_name,fn)=>fn());const endpoint=await stage('helper',()=>this.openTunnel(executable));const selected=this.state.models.find(m=>m.tag===s.model),existing=this.node(s.gateway),name=existing?.name||s.name,catalogueId=selected?.catalogueId||null,domains=selected?.domains||null,headers=gatewayHeaders({'Content-Type':'application/json'});if(existing?.node_token)headers['X-Common-Node-Token']=existing.node_token;const body=JSON.stringify({name,operator:s.operator,endpoint_url:endpoint+'/v1',model_name:s.model,capability_text:selected?.description||`${s.model}, contributed through Common Desktop.`,region:null,cost_per_1k:0,domain_tags:domains,catalogue_id:catalogueId,worker_token:token,client:CLIENT});await stage('publicEndpoint',()=>this.probeEndpoint(endpoint,token,s.model));this.record('registration_started');let registration;await stage('registration',async()=>{registration=await this.register(s.gateway,headers,body);if(typeof registration.id!=='string'||typeof registration.node_token!=='string'||!registration.id||!registration.node_token)throw failure('GATEWAY_MALFORMED');});if(!registration.id||!registration.node_token)throw new Error('The gateway did not return a node identity.');this.registeredGateway=s.gateway;this.rememberNode(s.gateway,{id:registration.id,node_token:registration.node_token,name,catalogue_id:catalogueId,domain_tags:domains});this.record('registration_completed');await stage('worker',()=>this.verifyWorker());this.record('worker_ready');this.lastError=null;this.state.worker.status='Contributing';this.state.worker.nodeId=registration.id;this.emitState();}
 async openTunnel(executable){this.record('tunnel_starting');const tunnel=this.spawnTunnel(executable,['tunnel','--url','http://127.0.0.1:'+this.worker.port,'--no-autoupdate'],{windowsHide:true,stdio:['ignore','pipe','pipe']});this.tunnel=tunnel;const endpoint=await new Promise((resolve,reject)=>{let settled=false;let buffer='';const aborted=()=>finish(failure('TUNNEL_START_FAILED'));const timer=setTimeout(()=>finish(failure('TUNNEL_TIMEOUT')),45000);const finish=(error,value)=>{if(settled)return;settled=true;this.lifecycle.signal.removeEventListener('abort',aborted);clearTimeout(timer);tunnel.stdout.removeListener('data',read);tunnel.stderr.removeListener('data',read);tunnel.removeListener('error',failed);tunnel.removeListener('exit',exited);error?reject(error):resolve(value);};const read=chunk=>{buffer=(buffer+chunk.toString()).slice(-12000);const match=buffer.match(/https:\/\/(?!api\.)[a-z0-9-]+\.trycloudflare\.com/);if(match)finish(null,match[0]);},failed=()=>finish(failure('TUNNEL_START_FAILED')),exited=()=>{const {message,retryAfter}=helperExit(buffer),error=failure(retryAfter?'TUNNEL_RATE_LIMITED':'TUNNEL_START_FAILED');if(retryAfter)error.retryAfter=retryAfter;finish(error);};this.lifecycle.signal.addEventListener('abort',aborted,{once:true});tunnel.stdout.on('data',read);tunnel.stderr.on('data',read);tunnel.once('error',failed);tunnel.once('exit',exited);});this.endpoint=endpoint;this.record('tunnel_connected');tunnel.stdout.resume();tunnel.stderr.resume();tunnel.on('error',()=>{});tunnel.once('exit',()=>{if(this.tunnel===tunnel){this.workerVerified=false;this.record('worker_disconnected');this.record('tunnel_failed',{code:'TUNNEL_START_FAILED'});this.worker?.pause();this.state.worker.status='Connection interrupted — reconnecting';this.emitState();this.reconcile().catch(()=>{});}});return endpoint;}

 // A quick tunnel's hostname is not resolvable the moment cloudflared prints
 // it. Measured against the production gateway: public DNS answers at ~20s,
 // and the gateway accepts at ~80s -- its resolver caches the NXDOMAIN it got
 // first. The gateway resolves endpoint_url at registration time as SSRF
 // defence and 400s what it cannot resolve, so registering straight away
 // always loses that race.
 //
 // Losing it used to be fatal: reconcile tore the tunnel down, waited 30s and
 // opened a NEW tunnel with a NEW hostname, which lost again -- a contributor
 // stuck on "Connecting" forever, with nothing in the registry. So wait here,
 // on this tunnel, rather than throwing away the hostname that is about to
 // start working. Only the does-not-resolve 400 is retried; every other
 // failure still surfaces immediately.
 async register(gateway,headers,body,{attempts=12,delay=15000,sleep=ms=>require('node:timers/promises').setTimeout(ms,null,{signal:this.lifecycle.signal})}={}){
  for(let i=0;;i++){
   this.lifecycle.signal.throwIfAborted();try{return await json(gateway+'/nodes',{method:'POST',headers,body,signal:AbortSignal.any([this.lifecycle.signal,AbortSignal.timeout(12000)])});}
   catch(e){
    if(i>=attempts-1||this.closed||e.code!=='endpoint_dns_pending')throw e;
    this.state.worker.status='Waiting for the connection address to go live';this.emitState();
    await sleep(delay);
    if(this.closed)throw e;
   }
  }
 }
 async stopWorker({preserveRegistration=false}={}){this.workerVerified=false;this.endpoint=null;const w=this.worker;this.worker=null;w?.pause();const t=this.tunnel;this.tunnel=null;t?.kill();if(w)await w.close();const g=this.registeredGateway;if(!preserveRegistration)this.registeredGateway=null;const node=g&&this.node(g);if(node){try{if(preserveRegistration){await checkedFetch(`${g}/nodes/${encodeURIComponent(node.id)}/pause`,{method:'POST',headers:gatewayHeaders({'X-Common-Node-Token':node.node_token}),signal:AbortSignal.timeout(5000)});}else{await checkedFetch(`${g}/nodes/${encodeURIComponent(node.id)}`,{method:'DELETE',headers:gatewayHeaders({'X-Common-Node-Token':node.node_token}),signal:AbortSignal.timeout(5000)});this.forgetNode(g);}}catch{/* Keep ownership for re-registration after an outage. */}}this.state.worker.status='Paused';this.state.worker.active=0;this.emitState();}
 async close(){if(this.closed)return;this.closed=true;this.lifecycle.abort();this.cancelChat();this.cancelDownload();await this.serial(()=>this.stopWorker());this.ownedOllama?.kill();this.reporting.clear();this.diagnostics.close();}
}
Object.assign(Service.prototype,require('./health.cjs').methods);
module.exports={Service,policy,helperExit,FALLBACK_MODELS};
