const fs=require('node:fs'),path=require('node:path'),{randomBytes}=require('node:crypto');
const DEFAULT_GATEWAY='https://gateway-production-b820.up.railway.app';
function normalizeGateway(value){const u=new URL(value);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw new Error('Use an HTTPS gateway URL, or localhost for development.');if(u.username||u.password||u.search||u.hash)throw new Error('Enter a gateway URL without credentials, query parameters or fragments.');return u.href.replace(/\/$/,'');}
class Settings{
 constructor(dir){this.file=path.join(dir,'settings.json');this.value={gateway:DEFAULT_GATEWAY,level:'user',role:'both',setupComplete:false,model:'llama3.2:3b',name:'common-'+randomBytes(5).toString('hex'),operator:'friend',idleOnly:true,idleMinutes:5,pauseBattery:true,startAtLogin:false,closeToTray:true,concurrency:1,contributing:false,identities:{},chatTokens:{}};try{this.value={...this.value,...JSON.parse(fs.readFileSync(this.file,'utf8'))};}catch(e){if(e.code!=='ENOENT')throw new Error('Common could not read settings.json. Back up that file before repairing it.');}this.value.gateway=normalizeGateway(this.value.gateway);}
 save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});fs.writeFileSync(this.file+'.tmp',JSON.stringify(this.value,null,2),{mode:0o600});fs.renameSync(this.file+'.tmp',this.file);}
 update(patch){const n={...this.value};for(const k of ['idleOnly','pauseBattery','startAtLogin','closeToTray','contributing','setupComplete'])if(k in patch){if(typeof patch[k]!=='boolean')throw new Error('Invalid preference.');n[k]=patch[k];}for(const [k,values]of Object.entries({level:['user','enthusiast','developer'],role:['chat','contribute','both']}))if(k in patch){if(!values.includes(patch[k]))throw new Error('Invalid option.');n[k]=patch[k];}if('gateway'in patch)n.gateway=normalizeGateway(patch.gateway);if('model'in patch){if(typeof patch.model!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,149}$/.test(patch.model)||/:cloud$/.test(patch.model))throw new Error('Choose a local Ollama model tag.');n.model=patch.model;}if('concurrency'in patch){if(![1,2].includes(patch.concurrency))throw new Error('Choose one or two jobs.');n.concurrency=patch.concurrency;}if('idleMinutes'in patch){if(![1,5,10,15,30].includes(patch.idleMinutes))throw new Error('Invalid idle delay.');n.idleMinutes=patch.idleMinutes;}if('chatToken'in patch){if(typeof patch.chatToken!=='string'||patch.chatToken.length>256||/[\r\n]/.test(patch.chatToken))throw new Error('Invalid token.');n.chatTokens={...n.chatTokens,[n.gateway]:patch.chatToken.trim()};}this.value=n;this.save();}
 public(){const {identities,chatTokens,...rest}=this.value;return {...rest,hasChatToken:!!chatTokens[rest.gateway],nodeId:identities[rest.gateway]?.id||null};}
}
module.exports={Settings,normalizeGateway,DEFAULT_GATEWAY};
